#!/bin/bash
# SessionStart hook — fires when a new Crunch session begins
# Reads memory files, logs the session start, and writes a fresh context
# snapshot to state/session-context.md for quick reference.
#
# Input JSON (on stdin): { timestamp, cwd, source, initialPrompt }
# Output: ignored by Copilot CLI — but we write to state/session-context.md

set -euo pipefail
INPUT=$(cat)
SOURCE=$(echo "$INPUT" | jq -r '.source // "unknown"' 2>/dev/null || echo "unknown")
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"
MEMORY_LOG="$REPO_ROOT/memory.log"
CONTEXT_OUT="$REPO_ROOT/state/session-context.md"

# Log session start
echo "[${TS}] HOOK:SessionStart source=${SOURCE}" >> "$MEMORY_LOG"

# Write a fresh context snapshot for this session
{
  echo "# Crunch Session Context"
  echo "_Auto-generated by SessionStart hook at ${TS}_"
  echo ""
  echo "## Recent memory (last 20 lines)"
  echo '```'
  tail -20 "$MEMORY_LOG" 2>/dev/null || echo "(no memory log)"
  echo '```'
  echo ""
  echo "## Identity"
  if [ -f "$REPO_ROOT/state/memory/crunch.md" ]; then
    head -20 "$REPO_ROOT/state/memory/crunch.md"
  fi
  echo ""
  echo "## Infrastructure snapshot"
  if [ -f "$REPO_ROOT/state/memory/infrastructure.md" ]; then
    head -30 "$REPO_ROOT/state/memory/infrastructure.md"
  fi
} > "$CONTEXT_OUT"

exit 0
